#!/bin/bash

# this is a comment

# for loop to count to 10
for c in {1..5}; do
	echo "Count: $c"

	# if does not use == it uses -eq
	# note the spaces around if [ ]
	if [ $c -eq 3 ]; then
		echo "found the third item"
	fi
done

# how do we pass parameters from the command line
# into this bash script. 
# we use the notation $1, $2 etc to represent
# the first, second etc parameter into this script
if [ -z $1 ]; then
	echo "You didn't pass any paraemters to $0"
else
	echo "You passed in $1 to $0"
fi

# heres a brand new command: 
# it calls ps -ef, then pipes it into word counter
# then stores the result in ct
ct=$(ps -ef | wc -l)
echo "There are $ct processes running on this machine"

# - Exercise 1 + 2
#-n$1 checks if the parameter is valid
#if count is greater than that parameter then output appropiate response.
if [ -n "$1" ]; then
    echo "Where would you like to output the results?"
    echo "1) Screen"
    echo "2) Log File"
    read -p "Enter choice (1 or 2): " choice

    if [ "$choice" -eq 1 ]; then
        if [ "$ct" -gt "$1" ]; then
            echo "Maximum number of processes exceeded"
        else
            echo "The maximum number of processes NOT exceeded"
        fi
    elif [ "$choice" -eq 2 ]; then
        date >> process_log.txt
        if [ "$ct" -gt "$1" ]; then
            echo "Maximum number of processes exceeded" >> process_log.txt
        else
            echo "The maximum number of processes NOT exceeded" >> process_log.txt
        fi
        echo "Results successfully written to process_log.txt"
    else
        echo "Invalid choice selected."
    fi
fi
